// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://liqdfaxmmqpovjptmaxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpcWRmYXhtbXFwb3ZqcHRtYXhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MDA1NzIsImV4cCI6MjA3MzI3NjU3Mn0.z8M6IHHaueOl_ZLfkvd_r_Hd_OAmmLZ9B7L3aGQv_XE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});